### ISSUE TITLE
Customize POST preservation page

### ISSUE THREAD

**Issue by kerrermanisNL** [OpenIDC/mod_auth_openidc#195]
Currently when posting a form, an authentication request is being performed and the `OIDCPreservePost` option is enabled a (or actually a couple) blank screen is shown with the text "Redirecting...". This page gets shown relatively long. It would be great if this page could either take less long, be customizable so it fits in better with the rest of the site or be avoided all together.

Any tips on how to go about this, or would this have to be implemented as a feature?

**Comment by zandbelt** [comment]
I haven't experienced this myself but I haven't done exhaustive testing either... Could you give a concrete example of the POST data that you send? Is it large and/or has many parameters?

FWIW: the text should say "Preserving..." rather than "Redirecting..." can you confirm that?

**Comment by kerrermanisNL** [comment]
Ah yes you're right. There are two pages shown, one showing "preserving..." which doesn't take too long. This then gets switched to "restoring..." which is the page that takes the longest (nothing too bad, but definitely noticeable. I would say around 1 second).

Example POST data (Django):
```
<QueryDict: {
    u'key_8_domain_16': [u'on'], 
    u'key_8_domain_17': [u'on'], 
    u'csrfmiddlewaretoken': [u'xxxxxxxxxxxxxxxxxxxxxxxx']
}>
```

**Comment by zandbelt** [comment]
I'm not a Javascript expert but I don't see how this code:
https://github.com/pingidentity/mod_auth_openidc/blob/master/src/mod_auth_openidc.c#L456
can be (much) more optimized. It pulls stuff from localstorage, uriDecodes it and puts in in the page dom...

**Comment by zandbelt** [comment]
Could it be that it is just the handler/page that it POSTs to is actually slow (i.e. your code :-O) ?

I do agree that a customizable screen would be a nice to have.

**Comment by kerrermanisNL** [comment]
It could be a possibility ;) Though I've noticed this over multiple pages and apps (though of course that doesn't say much).

In any case a customizable page would be very nice! A speed improvement is not my main wish at this point, I was just wondering if there was a possibility this was somewhere related in mod_auth_openidc.

**Comment by jamateo** [comment]
Hi!

We are looking for a way to customize the callback page that shows submitting. Unfortunately we can not compile the code in order to rewrite the part that shows this page. Is there any option to reference a flat html that shows other content?

Thank you!

**Comment by zandbelt** [comment]
No, not at this point, that's what this enhancement issue is about.

**Comment by jamateo** [comment]
Yep, 

I see, are you thinking about it? 

Thanks!

Regards

**Comment by zandbelt** [comment]
Prioritizing it would require a commercial discussion.

**Comment by jamateo** [comment]
Ok! 

Thanks a lot :)

Regards

**Comment by ajuvercr** [comment]
Bump, is there any new information about this?

**Comment by spiazzi** [comment]
Hi all,  

Hi, let me propose a change like this to read from config file a path of an html/js taken from a path, instead of a hardcoded js:

#include \<http\_config.h>  
#include \<apr\_file\_io.h>

/\*  
\* Function to generate HTML/JavaScript code from a file specified in the configuration  
\*/  
static apr\_byte\_t generate\_javascript\_from\_config(request\_rec \*r, const char \*location, char \*\*javascript, char \*\*javascript\_method) {  
   if (oidc\_cfg\_dir\_preserve\_post(r) == 0)  
       return FALSE;

   oidc\_debug(r, "enter");

   oidc\_cfg \*cfg = ap\_get\_module\_config(r->server->module\_config, &auth\_openidc\_module);

   const char \*method = oidc\_original\_request\_method(r, cfg, FALSE);

   if (\_oidc\_strcmp(method, OIDC\_METHOD\_FORM\_POST) != 0)  
       return FALSE;

   /\* Get the path to the JavaScript file from the configuration \*/  
   const char \*javascript\_file\_path = oidc\_get\_javascript\_file\_path(r);  
   if (!javascript\_file\_path) {  
       oidc\_error(r, "JavaScript file path not defined in configuration");  
       return FALSE;  
   }

   /\* Open the JavaScript file \*/  
   apr\_status\_t rv;  
   apr\_file\_t \*javascript\_file;  
   rv = apr\_file\_open(&javascript\_file, javascript\_file\_path, APR\_READ, APR\_OS\_DEFAULT, r->pool);  
   if (rv != APR\_SUCCESS) {  
       oidc\_error(r, "Failed to open JavaScript file");  
       return FALSE;  
   }

   /\* Read the content of the JavaScript file \*/  
   char \*jscript\_content;  
   rv = apr\_file\_read\_full(javascript\_file, jscript\_content, -1, NULL);  
   if (rv != APR\_SUCCESS) {  
       apr\_file\_close(javascript\_file);  
       oidc\_error(r, "Failed to read JavaScript file");  
       return FALSE;  
   }

   /\* Close the JavaScript file \*/  
   apr\_file\_close(javascript\_file);

   const char \*jmethod = "preserveOnLoad";  
   const char \*jscript = jscript\_content;

   if (location == NULL) {  
       if (javascript\_method)  
           \*javascript\_method = apr\_pstrdup(r->pool, jmethod);  
       if (javascript)  
           \*javascript = apr\_pstrdup(r->pool, jscript);  
   } else {  
       oidc\_util\_html\_send(r, "Preserving...", jscript, jmethod, "\<p>Preserving...\</p>", OK);  
   }

   return TRUE;  
}

/\*  
\* Function to get the path to the JavaScript file from the configuration  
\*/  
static const char \*oidc\_get\_javascript\_file\_path(request\_rec \*r) {  
   oidc\_cfg \*cfg = ap\_get\_module\_config(r->server->module\_config, &auth\_openidc\_module);

   const char \*javascript\_file\_path = cfg->javascript\_file\_path;

   if (!javascript\_file\_path || \*javascript\_file\_path == '\\0') {  
       return NULL;  
   }

   return ap\_server\_root\_relative(r->pool, javascript\_file\_path);  
}

  
It seems quite simple to achive - what do you think?

**Comment by zandbelt** [comment]
sure, please test and submit as a PR and we'll take it from there
